### PR TITLE
Added support for nested keys

### PR DESCRIPTION
**Pull request by faizanu94**
Module functionality implemented through `map-obj` NPM module and added support for nested keys as well

### CODE REVIEW

**Comment by sindresorhus** [comment]
I prefer to keep this package simple. Can you add a tip about using `map-obj` directly in the readme instead?

**Comment by faizanu94** [comment]
You mean this package shouldn't serve this purpose and instead the readme for `map-obj` should contain this tip?

**Comment by sindresorhus** [comment]
Correct

**Comment by faizanu94** [comment]
It's done (https://github.com/sindresorhus/map-obj/pull/30) for your approval

**Pull request closed without merging**
